"""add_vat_fields

Revision ID: de3425de9d0d
Revises: 
Create Date: 2026-03-19 05:05:24.788000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3425de9d0d'
down_revision: Union[str, None] = "000000000001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_settings', 'pdf_template',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'modern'::character varying"))
    op.add_column('documents', sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('line_items', sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False, server_default='8.10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_items', 'vat_rate')
    op.drop_column('documents', 'vat_amount')
    op.alter_column('company_settings', 'pdf_template',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'modern'::character varying"))
    # ### end Alembic commands ###
