#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
# status.sh — regenerate STATUS.md (repo snapshot for humans and agents)
#
#   ./scripts/status.sh        # or: make status
#
# Everything is derived from the tree: nothing here is typed by hand.
# ─────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

OUT="STATUS.md"
BACKEND="backend"
FRONTEND="frontend"

# ── Version: FastAPI(version="x.y.z") in backend/app/main.py ──────────
version="$(grep -oE 'version="[0-9]+\.[0-9]+\.[0-9]+"' "$BACKEND/app/main.py" | head -1 | cut -d'"' -f2)"
[[ -n "$version" ]] || version="unknown"

# ── Counts ─────────────────────────────────────────────────────────────
count_matches() {
  # Sum of `grep -c` over all files: total occurrences, not files.
  local pattern="$1"; shift
  grep -rc --include='*.py' "$pattern" "$@" 2>/dev/null | awk -F: '{s += $NF} END {print s + 0}'
}

backend_tests="$(count_matches 'def test_' "$BACKEND/tests")"
backend_test_files="$(find "$BACKEND/tests" -name 'test_*.py' | wc -l | tr -d ' ')"
vitest_files="$(find "$FRONTEND/src" -name '*.test.ts' -o -name '*.test.tsx' | wc -l | tr -d ' ')"
vitest_cases="$(grep -rhoE '^\s*(it|test)\(' "$FRONTEND/src" --include='*.test.ts' --include='*.test.tsx' 2>/dev/null | wc -l | tr -d ' ')"
e2e_specs="$(find "$FRONTEND/e2e" -name '*.spec.ts' | wc -l | tr -d ' ')"
e2e_cases="$(grep -rhoE '^\s*test\(' "$FRONTEND/e2e" --include='*.spec.ts' 2>/dev/null | wc -l | tr -d ' ')"
routers="$(grep -c 'app.include_router(' "$BACKEND/app/main.py" | tr -d ' ')"
routes="$(grep -rhoE '@router\.(get|post|put|patch|delete)\(' "$BACKEND/app/api" | wc -l | tr -d ' ')"
models="$(find "$BACKEND/app/models" -name '*.py' ! -name '__init__.py' | wc -l | tr -d ' ')"
migrations="$(find "$BACKEND/alembic/versions" -name '*.py' | wc -l | tr -d ' ')"

# Alembic head without importing anything: the revision that no other file
# names as its down_revision.
migration_head="$(
  cd "$BACKEND/alembic/versions" || exit 1
  revs="$(grep -hoE '^revision(: str)? = .[0-9a-f_]+' ./*.py | sed -E "s/.*= ['\"]//")"
  downs="$(grep -hoE '^down_revision(: (str|Union\[str, None\]|str \| None))? = .[0-9a-f_]+' ./*.py | sed -E "s/.*= ['\"]//")"
  for r in $revs; do
    grep -qx "$r" <<<"$downs" || echo "$r"
  done | head -1
)"
[[ -n "$migration_head" ]] || migration_head="unknown"

i18n_keys="$(grep -cE "^\s+'[a-zA-Z0-9_.]+':" "$FRONTEND/src/lib/i18n.ts" | tr -d ' ')"

# ── Roadmap ────────────────────────────────────────────────────────────
open_items="$(grep -cE '^- \[ \] \*\*R-' ROADMAP.md || true)"
done_items="$(grep -cE '^- \*\*R-[0-9]+[a-z]?\*\* ✅' ROADMAP.md || true)"
parked_items="$(grep -cE '^- \*\*P-[0-9]+\*\*' ROADMAP.md || true)"
next_r="$(grep -oE 'R-xx. = work item \(next free: \*\*R-[0-9]+' ROADMAP.md | grep -oE 'R-[0-9]+$' || echo '?')"
# First line of each open item (the file wraps by hand); pipes escaped for the table.
open_list="$(grep -E '^- \[ \] \*\*R-' ROADMAP.md \
  | sed -E 's/^- \[ \] \*\*(R-[0-9]+[a-z]?)\*\* (.*)$/\1\t\2/' \
  | awk -F'\t' '{ gsub(/\|/, "\\|", $2); printf "| %s | %s |\n", $1, $2 }')"

# ── Git ────────────────────────────────────────────────────────────────
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  commit="$(git rev-parse --short HEAD)"
  branch="$(git rev-parse --abbrev-ref HEAD)"
  commit_date="$(git log -1 --format=%cs)"
else
  commit="n/a"; branch="n/a"; commit_date="n/a"
fi
today="$(date +%Y-%m-%d)"

# ── Write ──────────────────────────────────────────────────────────────
{
  cat <<EOF
# STATUS — Billing

> Generated by \`scripts/status.sh\` (\`make status\`). Do not edit by hand.
> Last updated: **${today}** · branch \`${branch}\` @ \`${commit}\` (${commit_date})

| | |
|---|---|
| Version (\`backend/app/main.py\`) | **${version}** |
| Backend tests | **${backend_tests}** \`def test_\` in ${backend_test_files} files (\`backend/tests/\`) |
| Frontend unit tests | **${vitest_cases}** cases in ${vitest_files} vitest files (\`frontend/src/**/*.test.ts(x)\`) |
| E2E | **${e2e_cases}** Playwright tests in ${e2e_specs} specs (\`frontend/e2e/\`) |
| API | ${routers} routers · ${routes} routes (\`backend/app/api/\`) |
| Models | ${models} (\`backend/app/models/\`) |
| Migrations | ${migrations} · head \`${migration_head}\` (\`backend/alembic/versions/\`) |
| i18n entries | ${i18n_keys} (DE + EN dictionaries in \`frontend/src/lib/i18n.ts\`) |
| Roadmap | **${open_items} open** · ${done_items} done · ${parked_items} parked · next id ${next_r} (\`ROADMAP.md\`) |

## Open roadmap items

| ID | Item |
|---|---|
${open_list}

## How to verify

\`\`\`bash
make check          # lint + typecheck + backend + unit + e2e
make test-backend   # needs DATABASE_URL (see Makefile header)
make status         # regenerate this file
\`\`\`
EOF
} > "$OUT"

echo "wrote $OUT (v${version}, ${backend_tests} backend tests, ${open_items} open roadmap items)"
